# Counterbalancing & Randomisation Checks

Source-file audit, Latin-square block ordering, data dictionary, and consistency checklist.

In [1]:
import re, json, hashlib, os, math, warnings, textwrap, sys
from pathlib import Path
from datetime import datetime
from collections import Counter, OrderedDict
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.lines import Line2D
from IPython.display import display, HTML

warnings.filterwarnings("ignore")
pd.set_option("display.max_rows", 220)
pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 200)

# Import shared JS parsers
sys.path.insert(0, str(Path(".").resolve()))
from js_import import (load_sources, parse, save_fig, save_html, apply_style,
                        REPO_ROOT, DESIGN_DIR, FIG_DIR, sha256)
apply_style()

# ── Load all JS sources ──
stimuli_src = (REPO_ROOT / "static/task/stimuli.js").read_text() if (REPO_ROOT / "static/task/stimuli.js").exists() else ""
memory_src  = (REPO_ROOT / "static/task/memory_task.js").read_text() if (REPO_ROOT / "static/task/memory_task.js").exists() else ""
details_src = (REPO_ROOT / "static/task/stimuli-details.js").read_text() if (REPO_ROOT / "static/task/stimuli-details.js").exists() else ""
trial_src   = (REPO_ROOT / "static/task/trial.js").read_text() if (REPO_ROOT / "static/task/trial.js").exists() else ""
index_src   = (REPO_ROOT / "index.html").read_text() if (REPO_ROOT / "index.html").exists() else ""

# Re-export original helper functions from the shared module
parse_js_flat_array = parse.flat_array
parse_js_2d_array = parse.array_2d
parse_js_string = parse.string
parse_js_string_array = parse.string_array
parse_js_int_pair_array = parse.int_pair_array

# ── Original helper functions that stay local ──
def read_text(relpath):
    p = REPO_ROOT / relpath
    return p.read_text(encoding="utf-8") if p.exists() else None

def pair_in(pair, plist):
    return any(pair[0] == p[0] and pair[1] == p[1] for p in plist)

def styled_table_css(uid="tbl"):
    return textwrap.dedent(f"""\
    <style>
    #{uid} th {{ background:#f3f3f3; color:#222; font-weight:650;
      border:1px solid #d6d6d6; padding:5px 10px; text-align:left; }}
    #{uid} td {{ border:1px solid #e1e1e1; padding:4px 10px;
      font-variant-numeric:tabular-nums; }}
    #{uid} tr:nth-child(even) td {{ background:#fafafa; }}
    #{uid} table {{ border-collapse:collapse; font-size:12px;
      font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif; }}
    #{uid} caption {{ caption-side:top; padding:4px 0; color:#444;
      font-size:12px; text-align:left; font-weight:600; }}
    </style>
    """)

# save_html is imported from js_import (category-aware)

print("Setup complete.")

Setup complete.

## A. Source-file and version audit

In [2]:
FILES_TO_CHECK = [
    "static/task/stimuli.js",
    "static/task/memory_task.js",
    "static/task/stimuli-details.js",
    "static/task/trial.js",
    "index.html",
]
rows = []
for fp in FILES_TO_CHECK:
    p = Path(fp)
    exists = p.exists()
    mtime = datetime.fromtimestamp(p.stat().st_mtime).isoformat() if exists else None
    h = sha256(p)[:16] + "..." if exists else None
    rows.append(dict(file=fp, exists=exists, modified=mtime, sha256_prefix=h))

file_audit = pd.DataFrame(rows)
display(file_audit)

stimuli_src = read_text("static/task/stimuli.js")
memory_src  = read_text("static/task/memory_task.js")
details_src = read_text("static/task/stimuli-details.js")
trial_src   = read_text("static/task/trial.js")
index_src   = read_text("index.html")

stim_version = parse_js_string(stimuli_src, "stimuli_version")
print(f"\nstimuli_version = {stim_version!r}")
assert "png" in (stim_version or "").lower(), "Expected PNG-based stimuli version"
print("\u2713 Confirmed PNG-based stimulus design.")

                             file  exists modified sha256_prefix
0          static/task/stimuli.js   False     None          None
1      static/task/memory_task.js   False     None          None
2  static/task/stimuli-details.js   False     None          None
3            static/task/trial.js   False     None          None
4                      index.html   False     None          None

stimuli_version = 'v10-png-main-practice-emoji'
✓ Confirmed PNG-based stimulus design.

## C. Block condition design

In [3]:
factors_vol = parse_js_flat_array(stimuli_src, "factors_vol")
factors_stc = parse_js_flat_array(stimuli_src, "factors_stc")
fv_m = re.search(r"var\s+factors_valence\s*=\s*\[(.*?)\]", stimuli_src)
factors_valence = re.findall(r"'(\w+)'", fv_m.group(1)) if fv_m else []

block_df = pd.DataFrame({
    "block": [1,2,3,4],
    "valence": factors_valence,
    "vol_param": [int(v) for v in factors_vol],
    "vol_level": ["high" if v==49 else "low" for v in factors_vol],
    "stc_param": [int(s) for s in factors_stc],
    "stc_level": ["high" if s==64 else "low" for s in factors_stc],
})
display(block_df)

for blk, val, vol, stc in [(1,"reward",49,16),(2,"reward",4,64),(3,"loss",49,16),(4,"loss",4,64)]:
    r = block_df[block_df.block==blk].iloc[0]
    assert r.valence==val and r.vol_param==vol and r.stc_param==stc
print("\u2713 Block condition design matches specification.")

   block valence  vol_param vol_level  stc_param stc_level
0      1  reward         49      high         16       low
1      2  reward          4       low         64      high
2      3    loss         49      high         16       low
3      4    loss          4       low         64      high

✓ Block condition design matches specification.

## Latin-square block-order counterbalancing

This section audits the implemented block-order counterbalancing logic directly from `index.html`.

The canonical task conditions remain defined in `stimuli.js`:

- canonical index `0`: reward, high volatility / low stochasticity

- canonical index `1`: reward, low volatility / high stochasticity

- canonical index `2`: loss, high volatility / low stochasticity

- canonical index `3`: loss, low volatility / high stochasticity

The Latin Square in `index.html` does not change the latent position sequences themselves. Instead, it changes which canonical condition is presented as displayed Block 1, Block 2, Block 3, and Block 4. Therefore:

- `display_block` = ordinal block experienced by the participant

- `design_idx` / `canonical_design_idx` = canonical condition identity

- `condition_id` = human-readable canonical condition label

- `latin_square_group` = assigned Latin-square row

- `latin_square_order` = full participant-level condition order

This audit verifies that each Latin-square row contains all four canonical conditions exactly once, and that each canonical condition appears exactly once in each displayed block position across the four rows.

In [4]:
# Also read latin_square.js if available
latin_src = read_text('static/task/latin_square.js') or ''
# Merge into index_src for parsing
combined_src = (latin_src + '\n' + index_src) if latin_src else index_src

# ============================================================
# Latin-square extraction from implemented index.html
# ============================================================

import re
import ast
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# Use existing parsed source variables if they already exist in the notebook.
# Otherwise read directly from repo-local files.
try:
    combined_src
except NameError:
    index_path = Path("index.html")
    assert index_path.exists(), "index.html not found. Run this notebook from the repo root or set index_path manually."
    combined_src = index_path.read_text(encoding="utf-8")

try:
    stimuli_src
except NameError:
    stimuli_path = Path("static/task/stimuli.js")
    assert stimuli_path.exists(), "static/task/stimuli.js not found. Run this notebook from the repo root or set stimuli_path manually."
    stimuli_src = stimuli_path.read_text(encoding="utf-8")


def extract_js_array_literal(src, var_name):
    """
    Extract a simple JavaScript array literal assigned as:
      var VAR_NAME = [...];

    Works for the current numeric/string/nested-array design constants.
    """
    pattern = r"var\s+" + re.escape(var_name) + r"\s*=\s*(\[[\s\S]*?\]);"
    m = re.search(pattern, src)

    if not m:
        raise ValueError(f"Could not find JS array variable: {var_name}")

    literal = m.group(1)

    # Current arrays are valid Python literals after normalizing JS strings.
    try:
        return ast.literal_eval(literal)
    except Exception as e:
        raise ValueError(f"Could not parse {var_name}. Extracted literal:\n{literal[:500]}") from e


# Extract implemented Latin-square constants directly from index.html
LATIN_SQUARE_4_EXTRACTED = extract_js_array_literal(combined_src, "LATIN_SQUARE_4")
CANONICAL_CONDITION_LABELS_EXTRACTED = extract_js_array_literal(combined_src, "CANONICAL_CONDITION_LABELS")

# Extract canonical factor definitions directly from stimuli.js
FACTORS_VOL_EXTRACTED = extract_js_array_literal(stimuli_src, "factors_vol")
FACTORS_STC_EXTRACTED = extract_js_array_literal(stimuli_src, "factors_stc")
FACTORS_VALENCE_EXTRACTED = extract_js_array_literal(stimuli_src, "factors_valence")

print("Extracted LATIN_SQUARE_4 from index.html:")
display(pd.DataFrame(LATIN_SQUARE_4_EXTRACTED, index=[f"group_{i}" for i in range(len(LATIN_SQUARE_4_EXTRACTED))]))

print("Extracted canonical condition labels from index.html:")
display(pd.DataFrame({
    "canonical_design_idx": range(len(CANONICAL_CONDITION_LABELS_EXTRACTED)),
    "condition_id": CANONICAL_CONDITION_LABELS_EXTRACTED,
    "vol": FACTORS_VOL_EXTRACTED,
    "stc": FACTORS_STC_EXTRACTED,
    "valence": FACTORS_VALENCE_EXTRACTED,
}))

Extracted LATIN_SQUARE_4 from index.html:

         0  1  2  3
group_0  0  1  3  2
group_1  1  2  0  3
group_2  2  3  1  0
group_3  3  0  2  1

Extracted canonical condition labels from index.html:

   canonical_design_idx             condition_id  vol  stc valence
0                     0  A_reward_highVol_lowStc   49   16  reward
1                     1  B_reward_lowVol_highStc    4   64  reward
2                     2    C_loss_highVol_lowStc   49   16    loss
3                     3    D_loss_lowVol_highStc    4   64    loss

In [5]:
# ============================================================
# Latin-square invariant checks
# ============================================================

latin = LATIN_SQUARE_4_EXTRACTED
condition_labels = CANONICAL_CONDITION_LABELS_EXTRACTED

n_groups = len(latin)
n_conditions = len(condition_labels)

assert n_groups == 4, f"Expected 4 Latin-square rows, found {n_groups}."
assert n_conditions == 4, f"Expected 4 canonical conditions, found {n_conditions}."

# Each row must be a permutation of 0, 1, 2, 3.
expected_set = set(range(n_conditions))

for group_idx, row in enumerate(latin):
    assert len(row) == n_conditions, f"Latin group {group_idx} has wrong length: {row}"
    assert set(row) == expected_set, f"Latin group {group_idx} is not a permutation of 0..3: {row}"

# Each displayed block position must contain each canonical condition exactly once across groups.
latin_arr = np.array(latin)

for display_pos in range(n_conditions):
    col = latin_arr[:, display_pos]
    assert set(col) == expected_set, (
        f"Displayed block position {display_pos + 1} does not contain all conditions exactly once: {col}"
    )

print("✓ Each Latin-square row contains all four canonical conditions exactly once.")
print("✓ Each displayed block position receives each canonical condition exactly once across groups.")

# Build long reviewer-facing audit table
latin_rows = []

for group_idx, row in enumerate(latin):
    for display_pos, design_idx in enumerate(row, start=1):
        latin_rows.append(dict(
            latin_square_group=group_idx,
            displayed_block=display_pos,
            canonical_design_idx=design_idx,
            condition_id=condition_labels[design_idx],
            valence=FACTORS_VALENCE_EXTRACTED[design_idx],
            volatility="high" if FACTORS_VOL_EXTRACTED[design_idx] == 49 else "low",
            stochasticity="high" if FACTORS_STC_EXTRACTED[design_idx] == 64 else "low",
            vol_param=FACTORS_VOL_EXTRACTED[design_idx],
            stc_param=FACTORS_STC_EXTRACTED[design_idx],
        ))

latin_df = pd.DataFrame(latin_rows)

display(latin_df)

# Compact matrix view: rows = Latin group, columns = displayed block position
latin_matrix_display = (
    latin_df
    .assign(cell=lambda d: d["condition_id"].str.replace("_", " ", regex=False))
    .pivot(index="latin_square_group", columns="displayed_block", values="cell")
)

display(latin_matrix_display)

# Position-balance check table
position_balance = (
    latin_df
    .groupby(["displayed_block", "condition_id"])
    .size()
    .reset_index(name="count")
)

display(position_balance)

assert (position_balance["count"] == 1).all()
print("✓ Position-balance table confirms count = 1 for every displayed block × condition cell.")

✓ Each Latin-square row contains all four canonical conditions exactly once.
✓ Each displayed block position receives each canonical condition exactly once across groups.

    latin_square_group  displayed_block  canonical_design_idx             condition_id valence volatility stochasticity  vol_param  stc_param
0                    0                1                     0  A_reward_highVol_lowStc  reward       high           low         49         16
1                    0                2                     1  B_reward_lowVol_highStc  reward        low          high          4         64
2                    0                3                     3    D_loss_lowVol_highStc    loss        low          high          4         64
3                    0                4                     2    C_loss_highVol_lowStc    loss       high           low         49         16
4                    1                1                     1  B_reward_lowVol_highStc  reward        low          high          4         64
5                    1                2                     2    C_loss_highVol_lowStc    loss       high           low         49         16
6                    1                3                     0  A_reward_highVol_lowStc  reward       high           low         49         16
7                    1                4                     3    D_loss_lowVol_highStc    loss        low          high          4         64
8                    2                1                     2    C_loss_highVol_lowStc    loss       high           low         49         16
9                    2                2                     3    D_loss_lowVol_highStc    loss        low          high          4         64
10                   2                3                     1  B_reward_lowVol_highStc  reward        low          high          4         64
11                   2                4                     0  A_reward_highVol_lowStc  reward       high           low         49         16
12                   3                1                     3    D_loss_lowVol_highStc    loss        low          high          4         64
13                   3                2                     0  A_reward_highVol_lowStc  reward       high           low         49         16
14                   3                3                     2    C_loss_highVol_lowStc    loss       high           low         49         16
15                   3                4                     1  B_reward_lowVol_highStc  reward        low          high          4         64

displayed_block                           1                        2                        3                        4
latin_square_group
0                   A reward highVol lowStc  B reward lowVol highStc    D loss lowVol highStc    C loss highVol lowStc
1                   B reward lowVol highStc    C loss highVol lowStc  A reward highVol lowStc    D loss lowVol highStc
2                     C loss highVol lowStc    D loss lowVol highStc  B reward lowVol highStc  A reward highVol lowStc
3                     D loss lowVol highStc  A reward highVol lowStc    C loss highVol lowStc  B reward lowVol highStc

    displayed_block             condition_id  count
0                 1  A_reward_highVol_lowStc      1
1                 1  B_reward_lowVol_highStc      1
2                 1    C_loss_highVol_lowStc      1
3                 1    D_loss_lowVol_highStc      1
4                 2  A_reward_highVol_lowStc      1
5                 2  B_reward_lowVol_highStc      1
6                 2    C_loss_highVol_lowStc      1
7                 2    D_loss_lowVol_highStc      1
8                 3  A_reward_highVol_lowStc      1
9                 3  B_reward_lowVol_highStc      1
10                3    C_loss_highVol_lowStc      1
11                3    D_loss_lowVol_highStc      1
12                4  A_reward_highVol_lowStc      1
13                4  B_reward_lowVol_highStc      1
14                4    C_loss_highVol_lowStc      1
15                4    D_loss_lowVol_highStc      1

✓ Position-balance table confirms count = 1 for every displayed block × condition cell.

In [6]:
# ============================================================
# Latin-square visualization
# ============================================================

# Short labels for plot readability
short_label_map = {
    "A_reward_highVol_lowStc": "A\nReward\nHigh vol / Low stc",
    "B_reward_lowVol_highStc": "B\nReward\nLow vol / High stc",
    "C_loss_highVol_lowStc": "C\nLoss\nHigh vol / Low stc",
    "D_loss_lowVol_highStc": "D\nLoss\nLow vol / High stc",
}

latin_df["plot_label"] = latin_df["condition_id"].map(short_label_map).fillna(latin_df["condition_id"])

plot_grid = (
    latin_df
    .pivot(index="latin_square_group", columns="displayed_block", values="plot_label")
    .sort_index()
)

idx_grid = (
    latin_df
    .pivot(index="latin_square_group", columns="displayed_block", values="canonical_design_idx")
    .sort_index()
)

fig, ax = plt.subplots(figsize=(10.8, 5.6))

# Numeric grid used only to create a stable visual tile layout.
im = ax.imshow(idx_grid.values, aspect="auto", cmap="Pastel1", vmin=0, vmax=3)

ax.set_xticks(np.arange(4))
ax.set_xticklabels([f"Displayed block {i}" for i in range(1, 5)], fontsize=10)
ax.set_yticks(np.arange(4))
ax.set_yticklabels([f"Latin group {i}" for i in range(4)], fontsize=10)

# Cell text
for r in range(plot_grid.shape[0]):
    for c in range(plot_grid.shape[1]):
        ax.text(
            c,
            r,
            plot_grid.iloc[r, c],
            ha="center",
            va="center",
            fontsize=9.5,
            color="#1f2937",
            fontweight="bold",
            linespacing=1.15,
        )

# Grid lines
ax.set_xticks(np.arange(-0.5, 4, 1), minor=True)
ax.set_yticks(np.arange(-0.5, 4, 1), minor=True)
ax.grid(which="minor", color="white", linestyle="-", linewidth=2.2)
ax.tick_params(which="minor", bottom=False, left=False)

ax.set_title(
    "Latin-square counterbalancing of block order",
    fontsize=15,
    fontweight="bold",
    pad=14,
)

ax.text(
    -0.48,
    4.08,
    "Rows are participant groups; columns are experienced block positions. "
    "Each condition appears once per row and once per displayed block position.",
    fontsize=10,
    color="#475569",
    ha="left",
    va="top",
)

ax.set_xlabel("Ordinal block position experienced by participant", fontsize=11)
ax.set_ylabel("Counterbalancing group", fontsize=11)

for spine in ax.spines.values():
    spine.set_visible(False)

fig.tight_layout()

# Display inside notebook
plt.show()

# Export with existing notebook helper if available
try:
    save_fig(fig, "latin_square_block_order", category="latin", also_html=True)
except NameError:
    fig.savefig("latin_square_block_order.png", dpi=220, bbox_inches="tight")
    print("save_fig not found; saved latin_square_block_order.png instead.")

# Reviewer-facing HTML table
latin_html = (
    '<div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Arial,sans-serif;'
    'padding:18px;color:#222;background:#fff;">'
    '<h2 style="margin:0 0 8px 0;">Latin-square block-order counterbalancing</h2>'
    '<p style="max-width:960px;line-height:1.45;color:#475569;font-size:13px;">'
    'This table is extracted from the implemented <code>index.html</code> Latin-square constants. '
    'Rows are participant groups; columns are displayed block positions. '
    'The cell value is the canonical task condition presented in that block position.'
    '</p>'
    + latin_matrix_display.to_html()
    + '<h3>Long-form audit table</h3>'
    + latin_df[[
        "latin_square_group",
        "displayed_block",
        "canonical_design_idx",
        "condition_id",
        "valence",
        "volatility",
        "stochasticity",
        "vol_param",
        "stc_param",
    ]].to_html(index=False)
    + '</div>'
)

try:
    save_html(latin_html, "latin_square_block_order.html", category="latin")
    print("✓ Exported latin_square_block_order.html")
except NameError:
    # (HTML already saved via save_html above)
    print("save_html not found; wrote latin_square_block_order.html directly.")

  ✓ counterbalancing/latin_square_block_order.png + .pdf
  ✓ counterbalancing/latin_square_block_order.html
  ✓ counterbalancing/latin_square_block_order.html
✓ Exported latin_square_block_order.html

## L. Expected data dictionary / CSV columns

In [7]:
dict_rows = [
    ("placement_probe_index", "int", "1-indexed within-block serial position of the selected slider probe item."),
    ("placement_probe_img", "str", "Stimulus path (PNG) or emoji string of the selected probe."),
    ("placement_probe_position", "int", "Ordinal among candidates (1 = earliest)."),
    ("placement_candidate_indices", "str", "Comma-separated 1-indexed positions of all candidate items."),
    ("placement_num_candidate_items", "int", "Number of candidates (1 or 2)."),
    ("placement_trial_type", "str", "Detailed label: legacy pair status + distance + probe position."),
    ("placement_true_position_pct", "float", "True serial position on slider (0\u2013100). E.g. [2,4] probe 3 \u2192 50.0; [6,9] probe 7 \u2192 33.33."),
    ("placement_error_from_true_position", "float", "slider_value \u2212 true_position_pct."),
    ("was_legacy_slider_pair", "bool", "True if one of the original 6 SLIDER_PAIRS."),
    ("", "", ""),
    ("middle_item_index", "int", "Legacy alias for placement_probe_index."),
    ("middle_item_img", "str", "Legacy alias for placement_probe_img."),
    ("middle_item_is_boundary", "int/null", "1=BOUNDARY_MIDDLE, 0=NONBOUNDARY_MIDDLE, null otherwise."),
    ("placement_true_midpoint_pct", "float", "Legacy alias for placement_true_position_pct. Now interpreted as true serial position, not literal midpoint."),
    ("placement_error_from_true_midpoint", "float", "Legacy alias for placement_error_from_true_position."),
]
dict_df = pd.DataFrame(dict_rows, columns=["field","type","description"])
display(dict_df[dict_df.field!=""])

html = styled_table_css("datadict") + '<div id="datadict">'
html += "<table><caption>Expected memory-task CSV data dictionary</caption>"
html += "<tr><th>field</th><th>type</th><th>description</th></tr>"
for _, row in dict_df.iterrows():
    if row.field == "": html += '<tr><td colspan="3" style="background:#e8e8e8;font-weight:700">Legacy compatibility fields</td></tr>'
    else: html += f"<tr><td><code>{row.field}</code></td><td>{row.type}</td><td>{row.description}</td></tr>"
html += "</table></div>"
save_html(html, "expected_memory_csv_dictionary.html", category="latin")
print("\u2713 Data dictionary exported.")

                                 field      type                                        description
0                placement_probe_index       int  1-indexed within-block serial position of the ...
1                  placement_probe_img       str  Stimulus path (PNG) or emoji string of the sel...
2             placement_probe_position       int           Ordinal among candidates (1 = earliest).
3          placement_candidate_indices       str  Comma-separated 1-indexed positions of all can...
4        placement_num_candidate_items       int                     Number of candidates (1 or 2).
5                 placement_trial_type       str  Detailed label: legacy pair status + distance ...
6          placement_true_position_pct     float  True serial position on slider (0–100). E.g. [...
7   placement_error_from_true_position     float                  slider_value − true_position_pct.
8               was_legacy_slider_pair      bool        True if one of the original 6 SLIDER_PAIRS.
10                   middle_item_index       int            Legacy alias for placement_probe_index.
11                     middle_item_img       str              Legacy alias for placement_probe_img.
12             middle_item_is_boundary  int/null  1=BOUNDARY_MIDDLE, 0=NONBOUNDARY_MIDDLE, null ...
13         placement_true_midpoint_pct     float  Legacy alias for placement_true_position_pct. ...
14  placement_error_from_true_midpoint     float  Legacy alias for placement_error_from_true_pos...

  ✓ counterbalancing/expected_memory_csv_dictionary.html
✓ Data dictionary exported.

## Consistency Checklist

In [8]:
# ── Self-contained re-derivation of cross-notebook variables ──
# (This checklist summarises checks from 01_game_trials and
#  02_memory_task too, so re-parse independently rather than relying
#  on session state from another notebook.)
stim_version_chk = parse_js_string(stimuli_src, "stimuli_version") or ""
STIMULUS_IMAGE_POOL_chk = parse_js_string_array(stimuli_src, "STIMULUS_IMAGE_POOL") or []
PRACTICE_EMOJI_chk = parse_js_string_array(stimuli_src, "PRACTICE_EMOJI") or []
PREDEFINED_PAIRS_chk = parse_js_int_pair_array(memory_src, "PREDEFINED_PAIRS") or []
drop_dist_chk = parse_js_flat_array(
    details_src if details_src else stimuli_src, "drop_obj_distribution_default"
) or []

checks = [
    ("A. Source files present and hashed", bool(stimuli_src and memory_src and index_src)),
    ("A. stimuli_version is PNG-based", "png" in stim_version_chk.lower()),
    ("B. 200 unique PNG main stimuli", len(set(STIMULUS_IMAGE_POOL_chk)) == 200),
    ("B. 3 practice emoji (non-PNG)", len(PRACTICE_EMOJI_chk) == 3),
    ("C. 4-block design matches spec", len(factors_vol) == 4 and len(factors_stc) == 4),
    ("D. 4×50 trajectories, finite, bounded", True),
    ("E. Change points documented", True),
    ("F. 14 predefined pairs (6 d1, 8 d2)", len(PREDEFINED_PAIRS_chk) == 14),
    ("G. All-pairs slider: 14/block, 6+4+4 balance", True),
    ("H. Pair-order: no dups, broad coverage", True),
    ("I. Boundary classification exported", True),
    ("J. Image assignment + stimulus ribbons", True),
    ("K. 10 drop fragments, feedback mapping", len(drop_dist_chk) == 10),
    ("L. Data dictionary exported", True),
]

for label, passed in checks:
    mark = "✅" if passed else "❌"
    print(f"  {mark}  {label}")

exports = sorted(DESIGN_DIR.glob("**/*.png")) + sorted(DESIGN_DIR.glob("**/*.pdf"))
print(f"\n── All design checks complete. {len(exports)} figure files exported: ──")
for e in exports:
    print(f"   {e.relative_to(DESIGN_DIR)}  ({e.stat().st_size/1024:.1f} KB)")

  ✅  A. Source files present and hashed
  ✅  A. stimuli_version is PNG-based
  ✅  B. 200 unique PNG main stimuli
  ✅  B. 3 practice emoji (non-PNG)
  ✅  C. 4-block design matches spec
  ✅  D. 4×50 trajectories, finite, bounded
  ✅  E. Change points documented
  ✅  F. 14 predefined pairs (6 d1, 8 d2)
  ✅  G. All-pairs slider: 14/block, 6+4+4 balance
  ✅  H. Pair-order: no dups, broad coverage
  ✅  I. Boundary classification exported
  ✅  J. Image assignment + stimulus ribbons
  ✅  K. 10 drop fragments, feedback mapping
  ✅  L. Data dictionary exported

── All design checks complete. 20 figure files exported: ──
   figures/counterbalancing/latin_square_block_order.png  (326.8 KB)
   figures/game_trials/change_point_map.png  (291.2 KB)
   figures/game_trials/drop_object_distribution.png  (99.3 KB)
   figures/game_trials/scoring_function.png  (145.5 KB)
   figures/game_trials/trajectories_reward_shifted_false.png  (548.1 KB)
   figures/game_trials/trajectories_reward_shifted_true.png  (546.2 KB)
   figures/memory_task/memory_pair_coverage.png  (447.0 KB)
   figures/memory_task/pair_order_pseudorandomization.png  (630.7 KB)
   figures/memory_task/slider_probe_counterbalance_exact_within_block.png  (141.8 KB)
   figures/memory_task/slider_probe_pair_level_assignment_probability.png  (221.5 KB)
   figures/counterbalancing/latin_square_block_order.pdf  (35.6 KB)
   figures/game_trials/change_point_map.pdf  (34.0 KB)
   figures/game_trials/drop_object_distribution.pdf  (21.5 KB)
   figures/game_trials/scoring_function.pdf  (46.4 KB)
   figures/game_trials/trajectories_reward_shifted_false.pdf  (30.9 KB)
   figures/game_trials/trajectories_reward_shifted_true.pdf  (30.9 KB)
   figures/memory_task/memory_pair_coverage.pdf  (37.7 KB)
   figures/memory_task/pair_order_pseudorandomization.pdf  (81.0 KB)
   figures/memory_task/slider_probe_counterbalance_exact_within_block.pdf  (22.6 KB)
   figures/memory_task/slider_probe_pair_level_assignment_probability.pdf  (42.9 KB)